version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:alpha
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine, rocker_geo]
    default: nightly
  save-snapshots:
    type: boolean
    default: true

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build_and_check_package:
          executor: << pipeline.parameters.executor >>
          resource_class: small
          name: BuildAndCheckPackage
          context:
            - rviz_packages
          remote_deps: << pipeline.parameters.remote-deps >>
          separate_test_job: true
          save_snapshots: false
      - r-packages/test_package:
          executor: << pipeline.parameters.executor >>
          resource_class: small
          num_executors: 2
          name: TestPackage
          save_snapshots: << pipeline.parameters.save-snapshots >>
          requires:
            - BuildAndCheckPackage
          context:
            - rviz_packages
